Update major changes in datamodel and finish of get request endpoint
samBAM089/game-night-tracker pull request #31
Opened 2021-03-22 10:04 UTC by samBAM089

after realizing how the real data flow will be in the final application, I had to make some major changes.
mainly removed all Dbs and added a new one just for users.

methods and tests were all green.

2021-03-22 15:30 UTC, dride-for-sure requested changes

2021-03-22 15:38 UTC, samBAM089 commented on backend/src/main/java/de/sambam/gamenighttracker/db/UserDb.java
> +        this.userList.add(User.builder()
nice, i was wondering, why it did not take "List.of()" as Argument ^^

2021-03-22 15:38 UTC, samBAM089 commented on backend/src/main/java/de/sambam/gamenighttracker/db/UserDb.java
> +    }
that's for testing purposes ^^'

2021-03-22 16:06 UTC, samBAM089 commented on backend/src/main/java/de/sambam/gamenighttracker/db/UserDb.java
> +    }
well, if it was an native app, yes ^^'

2021-03-22 16:17 UTC, dride-for-sure commented on backend/src/main/java/de/sambam/gamenighttracker/db/UserDb.java
> +        this.userList.add(User.builder()
List.of() is possible true :)

2021-03-23 07:51 UTC, dride-for-sure approved these changes
So that your software also runs stable, I would swap maumau for dame! 🚀

2021-03-23 07:52 UTC, merged